services:
  postgres:
    image: postgres:16
    container_name: arch_postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: temp
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/psql/init:/docker-entrypoint-initdb.d
    networks:
      - arch_psql_net

  pgadmin:
    image: dpage/pgadmin4
    container_name: arch_pgadmin
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 1234
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - arch_psql_net

volumes:
  postgres_data:
  pgadmin_data:

networks:
  arch_psql_net:
