services:
  redis:
    image: redis:7-alpine
    container_name: redis_arch
    ports:
      - "6379:6379"
    networks:
      - arch_redis_net

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redis_insight
    ports:
      - "5540:5540"
    depends_on:
      - redis
    volumes:
      - redisinsight_data:/data
    restart: unless-stopped
    networks:
      - arch_redis_net

volumes:
  redisinsight_data:

networks:
  arch_redis_net:
