filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /usr/share/backend/logs/auth/*.json
    json.keys_under_root: true
    json.add_error_key: true
    json.message_key: log

output.logstash:
  hosts: ["logstash:5044"]
