global:
  scrape_interval: 5s

scrape_configs:

  - job_name: 'GATEWAY SERVER'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 2s
    static_configs:
      - targets: ["host.docker.internal:8500"]
        labels:
          application: 'Spring boot gateway server'


  - job_name: 'AUTH SERVER'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 2s
    static_configs:
      - targets: ["host.docker.internal:8510"]
        labels:
          application: 'Spring Boot Auth Server'

  - job_name: 'CHAT SERVER'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 2s
    static_configs:
      - targets: ["host.docker.internal:8500"]
        labels:
          application: 'Spring Boot Auth Server'
