global:
  scrape_interval: 15s

scrape_configs:

  - job_name: 'spring-auth-server'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 2s
    static_configs:
      - targets: ["host.docker.internal:8510"]
        labels:
          application: 'My Spring Boot Auth Server'
